### ISSUE TITLE
"attempt to index field 'CFWRK' (a nil value)" upon undoing a contraption

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/cframe#9]
Getting these errors in the server console upon removing any contraption spawned via Adv Dupe 2. As far as I can tell this error isn't breaking anything, but maybe worth fixing anyways.

![qOy2qpb](https://user-images.githubusercontent.com/21130637/77193296-689d0580-6ab4-11ea-9ec1-733da1f056f2.png)
![yQmtKN5](https://user-images.githubusercontent.com/21130637/77193427-9d10c180-6ab4-11ea-894d-6fc0cb008668.png)

**Comment by Stooberton** [comment]
Gonna close this since there's been a major overhaul and it may have been dealt with.
